#!/usr/bin/env python3
"""Derive the launcher box art and the window/executable icons from the logo.

    python tools/make_brand_assets.py

assets/urbanrecomp_logo.png is the master. The files written from it are
committed, so a build needs neither Python nor Pillow:

    assets/boxart.jpg          launcher box art (staged as assets/img/boxart.jpg)
    assets/icon.png            the launcher window's icon (assets/img/icon.png)
    assets/urbanrecomp.ico     embedded in the Windows executables (src/urbanrecomp.rc)
    assets/linux/icons/N.png   hicolor theme icons for the Linux desktop entry,
                               N = 16 ... 512, installed by CMakeLists.txt
    src/sc_icon_data.h         64x64 RGBA pixels compiled into the executable,
                               so every build sets a window icon (src/sc_icon.c)
"""
import os

from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
ASSETS = os.path.join(ROOT, "assets")
LINUX_SIZES = (16, 24, 32, 48, 64, 128, 256, 512)
EMBED = 64


def write_embedded(logo):
    px = logo.resize((EMBED, EMBED), Image.LANCZOS).convert("RGBA").tobytes()
    lines = []
    for i in range(0, len(px), 16):
        lines.append("  " + ", ".join("0x%02x" % b for b in px[i:i + 16]) + ",")
    text = "\n".join([
        "/* Generated by tools/make_brand_assets.py from assets/urbanrecomp_logo.png",
        " * -- do not edit. %dx%d RGBA, row by row. */" % (EMBED, EMBED),
        "#define SC_ICON_W %d" % EMBED,
        "#define SC_ICON_H %d" % EMBED,
        "static const unsigned char kScIconRgba[%d] = {" % len(px),
    ] + lines + ["};", ""])
    path = os.path.join(ROOT, "src", "sc_icon_data.h")
    with open(path, "w", newline="\n") as f:
        f.write(text)
    return path


def main():
    logo = Image.open(os.path.join(ASSETS, "urbanrecomp_logo.png")).convert("RGB")
    written = []

    p = os.path.join(ASSETS, "boxart.jpg")
    logo.resize((512, 512), Image.LANCZOS).save(p, quality=90, optimize=True)
    written.append(p)
    p = os.path.join(ASSETS, "icon.png")
    logo.resize((128, 128), Image.LANCZOS).convert("RGBA").save(p, optimize=True)
    written.append(p)
    p = os.path.join(ASSETS, "urbanrecomp.ico")
    logo.convert("RGBA").save(
        p, sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
    written.append(p)

    icons = os.path.join(ASSETS, "linux", "icons")
    os.makedirs(icons, exist_ok=True)
    for n in LINUX_SIZES:
        p = os.path.join(icons, "%d.png" % n)
        logo.resize((n, n), Image.LANCZOS).save(p, optimize=True)
        written.append(p)

    written.append(write_embedded(logo))
    for p in written:
        print("%-40s %8d bytes" % (os.path.relpath(p, ROOT), os.path.getsize(p)))


if __name__ == "__main__":
    main()
