/* Auto-generated by tools/select_pure_leaves.py -- do not hand-edit.
 *
 * AOT bodies that are pure leaves: no calls or non-local transfers,
 * no hardware-register access, small extent. These are the routines
 * where synthetic entry state is a fair test -- see the tool for why
 * that restriction exists. */
#define SC_PURE_LEAF_COUNT 34
static const struct { unsigned pc24, end; } kScPureLeaves[] = {
    { 0x00823Eu, 0x00824Au },
    { 0x00824Fu, 0x00825Eu },
    { 0x008436u, 0x008448u },
    { 0x008924u, 0x008969u },
    { 0x008982u, 0x0089C7u },
    { 0x00930Du, 0x009317u },
    { 0x00B584u, 0x00B601u },
    { 0x00C6D7u, 0x00C6E5u },
    { 0x00D23Au, 0x00D248u },
    { 0x00D9F2u, 0x00DA4Fu },
    { 0x01948Bu, 0x0194A2u },
    { 0x0194A7u, 0x0194E1u },
    { 0x01A0C2u, 0x01A0FDu },
    { 0x01AE26u, 0x01AE7Fu },
    { 0x01AFBEu, 0x01AFDBu },
    { 0x01B375u, 0x01B3E2u },
    { 0x01BA24u, 0x01BA3Eu },
    { 0x01C322u, 0x01C38Du },
    { 0x01C4C7u, 0x01C4E4u },
    { 0x01C7F6u, 0x01C7FCu },
    { 0x01F038u, 0x01F04Cu },
    { 0x02A651u, 0x02A66Du },
    { 0x02A9ADu, 0x02A9C0u },
    { 0x02AE4Au, 0x02AE5Cu },
    { 0x03A7DAu, 0x03A7DFu },
    { 0x03B0A3u, 0x03B0BDu },
    { 0x03B245u, 0x03B257u },
    { 0x03B258u, 0x03B26Au },
    { 0x03B554u, 0x03B561u },
    { 0x03BE04u, 0x03BE11u },
    { 0x03C11Au, 0x03C130u },
    { 0x03C50Au, 0x03C547u },
    { 0x0593CBu, 0x0593D3u },
    { 0x059FBBu, 0x059FE5u },
};
